#!/bin/sh
echo "AUTO: the @-command scripts are deprecated and will be removed; use the 'auto' CLI or the Python commands (run, load, save, ...)." 1>&2
if ( test $# -eq 1 ) then
	b1=b.$1
	s1=s.$1
	echo "Plotting b.$1 and s.$1 ..."
else
	b1=fort.7
	s1=fort.8
	echo "Plotting fort.7 and fort.8 ..."
fi
if [ -x "$AUTO_DIR"/bin/xterm-tek ]; then
	"$AUTO_DIR"/bin/xterm-tek -bg black -fg white -t -e "$AUTO_DIR"/bin/plaut $b1 $s1 &
else
	xterm -bg black -fg white -t -e "$AUTO_DIR"/bin/plaut $b1 $s1 &
fi
