#!/bin/sh
echo "AUTO: the @-command scripts are deprecated and will be removed; use the 'auto' CLI or the Python commands (run, load, save, ...)." 1>&2
for i in r.*; do
   mv $i c.${i#r.}
done
for i in s.*; do
   mv $i h.${i#s.}
done
for i in p.*; do
   mv $i b.${i#p.}
done
for i in q.*; do
   mv $i s.${i#q.}
done
