#!/bin/sh
echo "AUTO: the @-command scripts are deprecated and will be removed; use the 'auto' CLI or the Python commands (run, load, save, ...)." 1>&2
echo " "
echo " Zeroing small numbers in s.$1 ... "
make -f "$AUTO_DIR"/util/Makefile zero
cp s.$1 fort.28
mv s.$1 s.$1~
./zero
mv fort.38 s.$1
rm fort.28
rm zero
echo " Done. "
